# install task make tool: https://taskfile.dev/zh-Hans/installation/
#
version: '3'

vars:
  SRC_PATH: '{{.USER_WORKING_DIR}}'
  OUTPUT_BIN: 'project-template'
  OUTPUT_PATH: '{{.USER_WORKING_DIR}}/output'

tasks:
  gen:
    vars:
      PROTO_PATH: '{{.SRC_PATH}}/api'
      PROTO_FILE: '{{.SRC_PATH}}/api/v1/service.proto'

    cmds:
      - | 
        protoc \
          -I {{.PROTO_PATH}} \
          --go_out={{.PROTO_PATH}} \
          --go_opt=paths=source_relative \
          --go-grpc_out={{.PROTO_PATH}} \
          --go-grpc_opt=paths=source_relative \
          --validate_out="lang=go:{{.PROTO_PATH}}" \
          --validate_opt=paths=source_relative {{.PROTO_FILE}}

  wire:
    cmds:
      - cd {{.SRC_PATH}}/cmd/wireinject && wire
  
  clean:
    cmds:
      - rm -fr {{.OUTPUT_PATH}}
      - mkdir {{.OUTPUT_PATH}}

  build:
    deps:
      - clean
      - gen
      - wire
    vars:
      BUILD_DATE:
        sh: date +"%Y-%m-%d.%H:%m:%S"
      GIT_COMMIT:
        sh: git rev-parse --short HEAD

    cmds:
      - |
        CGO_ENABLED=0 \
        go build \
          -x \
          -ldflags "-X main.buildDate={{.BUILD_DATE}} -X main.buildCommit={{.GIT_COMMIT}}" \
          -o {{.OUTPUT_PATH}}/{{.OUTPUT_BIN}} \
          {{.SRC_PATH}}/cmd/main.go

  dev:
    deps:
      - gen
      - wire
    cmds:
      - go run {{.SRC_PATH}}/cmd/main.go

